### PR TITLE
Htm lftw

### PR DESCRIPTION
**Pull request by Joostdw1**
hi

### CODE REVIEW

**Comment by MemeButler** [comment]
Can one of the admins verify this patch?

**Comment by ChielBroere** [comment]
MemeButler please test this.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/4/

**Comment by Joostdw1** [comment]
test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/5/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/7/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/8/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/9/

**Pull request closed without merging**
