### PR TITLE
Merge conflict resolved

### PR DESCRIPTION
**Pull request by ChielBroere**

### CODE REVIEW

**Comment by MemeButler** [comment]
Nicely done!

**Comment by ChielBroere** [comment]
BUTLER! test this please.

**Comment by ChielBroere** [comment]
Test this please.

**Comment by ChielBroere** [comment]
Can one of the admins verify this patch?

**Comment by ChielBroere** [comment]
Can one of the admins verify this patch?

**Comment by ChielBroere** [comment]
Can one of the admins verify this patch?

**Comment by ChielBroere** [comment]
test this please.

**Comment by MemeButler** [comment]
Wow this is amazing!

**Pull request closed without merging**
