### PR TITLE
Unittests

### PR DESCRIPTION
**Pull request by ChielBroere**

### CODE REVIEW

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/31/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/33/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/34/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/36/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/38/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/39/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/40/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/43/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/44/

**Pull request closed without merging**
