### PR TITLE
Ik wil graag dat mijn takje samengevoegd wordt met de grote meester

### PR DESCRIPTION
**Pull request by FireStormHR**

### CODE REVIEW

**Comment by MemeButler** [comment]
Can one of the admins verify this patch?

**Comment by FireStormHR** [comment]
test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/13/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/14/

**Comment by ChielBroere** [comment]
ok to test.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/15/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/16/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/17/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/18/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/19/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/20/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/21/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Test3/23/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/2/

**Pull request closed without merging**
