### PR TITLE
Cool Unittests

### PR DESCRIPTION
**Pull request by ChielBroere**

### CODE REVIEW

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/3/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/5/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/6/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/10/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/11/

**Pull request merged**
