### PR TITLE
Help me please

### PR DESCRIPTION
**Pull request by ChielBroere**

### CODE REVIEW

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/22/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/23/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/24/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/25/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/26/

**Pull request closed without merging**
