### PR TITLE
Html and css

### PR DESCRIPTION
**Pull request by ChielBroere**

### CODE REVIEW

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/27/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/28/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/29/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/30/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/32/

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/35/

**Comment by ChielBroere** [comment]
MemeButler, test this please.

**Comment by MemeButler** [comment]
Refer to this link for build results (access rights to CI server needed): 
/job/Pipeline/37/

**Pull request merged**
